name: restaurant_app_api
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  google_fonts: 2.1.0
  rxdart: 0.27.2
  flutter_local_notifications: 9.0.0
  intl: 0.17.0
  android_alarm_manager: 2.0.2
  http: 0.13.4
  sqflite: 2.0.0+4
  path: 1.8.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  mockito: ^5.0.16
  build_runner: ^2.1.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

